version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dev_db
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
  postgres_test:
    image: postgres
    environment:
      - POSTGRES_USER=test_root
      - POSTGRES_PASSWORD=test_root
      - POSTGRES_DB=test_db
    ports:
      - 5433:5432
volumes:
  postgres:
